# Generated by Django 5.2.2 on 2025-07-14 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_consultarcomentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='consultarComentario',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='coment',
            new_name='comentario_alumno',
        ),
    ]
