# Generated by Django 5.2.2 on 2025-07-14 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_delete_consultarcomentario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario_alumno',
            new_name='coment',
        ),
    ]
